### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ellisgl** [LnsooXD/koa-socket-session#2]
```
{ event: 'message',
  data: { x: '1', y: '2' },
  socket: Connection {},
  acknowledge: undefined }
{}
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.<anonymous> (c:\xampp\htdocs\koatest\node_modules\koa-compose\index.js:35:19)
    at next (native)
    at onFulfilled (c:\xampp\htdocs\koatest\node_modules\co\index.js:65:19)
    at c:\xampp\htdocs\koatest\node_modules\co\index.js:54:5
    at Object.co (c:\xampp\htdocs\koatest\node_modules\co\index.js:50:10)
    at Object.toPromise (c:\xampp\htdocs\koatest\node_modules\co\index.js:118:63)
    at next (c:\xampp\htdocs\koatest\node_modules\co\index.js:99:29)
    at onFulfilled (c:\xampp\htdocs\koatest\node_modules\co\index.js:69:7)
    at c:\xampp\htdocs\koatest\node_modules\co\index.js:54:5
    at Object.co (c:\xampp\htdocs\koatest\node_modules\co\index.js:50:10)
```

```
const config           = require('./config');
const koa              = require('koa');
const koaSession       = require('koa-generic-session');
const koaSocketSession = require('koa-socket-session');
const MySQLStore       = require('koa-mysql-session');
const IO               = require('koa-socket.io');
const router           = require('koa-router');
const st               = require('koa-static');
const handlebars       = require('koa-handlebars');
const http             = require('http');
const app              = new koa();
const io               = new IO();
const _                = router(); //Instantiate the router

// init session
app.keys    = [config.sessionKey];
let session = koaSession({
                             store: new MySQLStore(config.db),
                             rolling: true,
                             cookie: {
                                 maxage: 2 * 60 * 1000
                             },
                             resave: true,
                             saveUninitialized: true
                         });

app.use(session);
app.use(st('./public'));
app.use(handlebars({}));
app.use(_.routes());

// init koa-socket-session as koa-socket's middleware
io.use(koaSocketSession(app, session));

io.on('message', (ctx, data) =>
{
    console.log(ctx);
    // get username from session
    //let username = ctx.session.username;
    // print the message received and username in session
    //console.log(`message: ${data}, username: ${username}`);
});

let server = http.createServer(app.callback());

io.start(server);

_.get('/', getIndex);

function *getIndex()
{
    this.session.username = 'LnsooXD';

    yield this.render("ssindex", {
        layout: "main",
        title: "GLAAS",
    });

}

/**
 app.use(function *()
 {
     // set username in session to 'LnsooXD'
     this.session.username = 'LnsooXD';
     this.body             = 'Hello World';
 });
 **/


server.listen(8080);
```

**Comment by fraxken** [comment]
- 1 , koa-socket-session seem to be deprecated for Koa2.x and more ( koa-socket.io work, but no shared session between)

**Comment by fraxken** [comment]
For 2.x for sure, but it does'nt work for 1.2 too...

**Comment by LnsooXD** [comment]
Let me have a look at this issue. This module just foe koa 1.x.
@fraxken

**Comment by LnsooXD** [comment]
Can you give me the "layouts/main" file please? @ellisgl
